// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

func testOptions(t *testing.T) {
	t.Parallel()

	query := Options(nil)

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}
func testOptionsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	option := &Option{}
	if err = randomize.Struct(seed, option, optionDBTypes, true, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = option.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = option.Delete(tx); err != nil {
		t.Error(err)
	}

	count, err := Options(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOptionsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	option := &Option{}
	if err = randomize.Struct(seed, option, optionDBTypes, true, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = option.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = Options(tx).DeleteAll(); err != nil {
		t.Error(err)
	}

	count, err := Options(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOptionsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	option := &Option{}
	if err = randomize.Struct(seed, option, optionDBTypes, true, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = option.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := OptionSlice{option}

	if err = slice.DeleteAll(tx); err != nil {
		t.Error(err)
	}

	count, err := Options(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}
func testOptionsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	option := &Option{}
	if err = randomize.Struct(seed, option, optionDBTypes, true, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = option.Insert(tx); err != nil {
		t.Error(err)
	}

	e, err := OptionExists(tx, option.ID)
	if err != nil {
		t.Errorf("Unable to check if Option exists: %s", err)
	}
	if !e {
		t.Errorf("Expected OptionExistsG to return true, but got false.")
	}
}
func testOptionsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	option := &Option{}
	if err = randomize.Struct(seed, option, optionDBTypes, true, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = option.Insert(tx); err != nil {
		t.Error(err)
	}

	optionFound, err := FindOption(tx, option.ID)
	if err != nil {
		t.Error(err)
	}

	if optionFound == nil {
		t.Error("want a record, got nil")
	}
}
func testOptionsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	option := &Option{}
	if err = randomize.Struct(seed, option, optionDBTypes, true, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = option.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = Options(tx).Bind(option); err != nil {
		t.Error(err)
	}
}

func testOptionsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	option := &Option{}
	if err = randomize.Struct(seed, option, optionDBTypes, true, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = option.Insert(tx); err != nil {
		t.Error(err)
	}

	if x, err := Options(tx).One(); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testOptionsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	optionOne := &Option{}
	optionTwo := &Option{}
	if err = randomize.Struct(seed, optionOne, optionDBTypes, false, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}
	if err = randomize.Struct(seed, optionTwo, optionDBTypes, false, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = optionOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = optionTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := Options(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testOptionsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	optionOne := &Option{}
	optionTwo := &Option{}
	if err = randomize.Struct(seed, optionOne, optionDBTypes, false, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}
	if err = randomize.Struct(seed, optionTwo, optionDBTypes, false, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = optionOne.Insert(tx); err != nil {
		t.Error(err)
	}
	if err = optionTwo.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Options(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}
func optionBeforeInsertHook(e boil.Executor, o *Option) error {
	*o = Option{}
	return nil
}

func optionAfterInsertHook(e boil.Executor, o *Option) error {
	*o = Option{}
	return nil
}

func optionAfterSelectHook(e boil.Executor, o *Option) error {
	*o = Option{}
	return nil
}

func optionBeforeUpdateHook(e boil.Executor, o *Option) error {
	*o = Option{}
	return nil
}

func optionAfterUpdateHook(e boil.Executor, o *Option) error {
	*o = Option{}
	return nil
}

func optionBeforeDeleteHook(e boil.Executor, o *Option) error {
	*o = Option{}
	return nil
}

func optionAfterDeleteHook(e boil.Executor, o *Option) error {
	*o = Option{}
	return nil
}

func optionBeforeUpsertHook(e boil.Executor, o *Option) error {
	*o = Option{}
	return nil
}

func optionAfterUpsertHook(e boil.Executor, o *Option) error {
	*o = Option{}
	return nil
}

func testOptionsHooks(t *testing.T) {
	t.Parallel()

	var err error

	empty := &Option{}
	o := &Option{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, optionDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Option object: %s", err)
	}

	AddOptionHook(boil.BeforeInsertHook, optionBeforeInsertHook)
	if err = o.doBeforeInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	optionBeforeInsertHooks = []OptionHook{}

	AddOptionHook(boil.AfterInsertHook, optionAfterInsertHook)
	if err = o.doAfterInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	optionAfterInsertHooks = []OptionHook{}

	AddOptionHook(boil.AfterSelectHook, optionAfterSelectHook)
	if err = o.doAfterSelectHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	optionAfterSelectHooks = []OptionHook{}

	AddOptionHook(boil.BeforeUpdateHook, optionBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	optionBeforeUpdateHooks = []OptionHook{}

	AddOptionHook(boil.AfterUpdateHook, optionAfterUpdateHook)
	if err = o.doAfterUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	optionAfterUpdateHooks = []OptionHook{}

	AddOptionHook(boil.BeforeDeleteHook, optionBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	optionBeforeDeleteHooks = []OptionHook{}

	AddOptionHook(boil.AfterDeleteHook, optionAfterDeleteHook)
	if err = o.doAfterDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	optionAfterDeleteHooks = []OptionHook{}

	AddOptionHook(boil.BeforeUpsertHook, optionBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	optionBeforeUpsertHooks = []OptionHook{}

	AddOptionHook(boil.AfterUpsertHook, optionAfterUpsertHook)
	if err = o.doAfterUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	optionAfterUpsertHooks = []OptionHook{}
}
func testOptionsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	option := &Option{}
	if err = randomize.Struct(seed, option, optionDBTypes, true, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = option.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Options(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOptionsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	option := &Option{}
	if err = randomize.Struct(seed, option, optionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = option.Insert(tx, optionColumnsWithoutDefault...); err != nil {
		t.Error(err)
	}

	count, err := Options(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOptionToManyVotes(t *testing.T) {
	var err error
	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Option
	var b, c Vote

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, optionDBTypes, true, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}

	randomize.Struct(seed, &b, voteDBTypes, false, voteColumnsWithDefault...)
	randomize.Struct(seed, &c, voteDBTypes, false, voteColumnsWithDefault...)

	b.OptionID = a.ID
	c.OptionID = a.ID
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx); err != nil {
		t.Fatal(err)
	}

	vote, err := a.Votes(tx).All()
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range vote {
		if v.OptionID == b.OptionID {
			bFound = true
		}
		if v.OptionID == c.OptionID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := OptionSlice{&a}
	if err = a.L.LoadVotes(tx, false, (*[]*Option)(&slice)); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Votes); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Votes = nil
	if err = a.L.LoadVotes(tx, true, &a); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Votes); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", vote)
	}
}

func testOptionToManyAddOpVotes(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Option
	var b, c, d, e Vote

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, optionDBTypes, false, strmangle.SetComplement(optionPrimaryKeyColumns, optionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Vote{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, voteDBTypes, false, strmangle.SetComplement(votePrimaryKeyColumns, voteColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Vote{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddVotes(tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.OptionID {
			t.Error("foreign key was wrong value", a.ID, first.OptionID)
		}
		if a.ID != second.OptionID {
			t.Error("foreign key was wrong value", a.ID, second.OptionID)
		}

		if first.R.Option != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Option != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Votes[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Votes[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Votes(tx).Count()
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testOptionToOneCatchUpUsingCatchUp(t *testing.T) {
	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var local Option
	var foreign CatchUp

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, optionDBTypes, false, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, catchUpDBTypes, false, catchUpColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CatchUp struct: %s", err)
	}

	if err := foreign.Insert(tx); err != nil {
		t.Fatal(err)
	}

	local.CatchUpID = foreign.ID
	if err := local.Insert(tx); err != nil {
		t.Fatal(err)
	}

	check, err := local.CatchUp(tx).One()
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := OptionSlice{&local}
	if err = local.L.LoadCatchUp(tx, false, (*[]*Option)(&slice)); err != nil {
		t.Fatal(err)
	}
	if local.R.CatchUp == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.CatchUp = nil
	if err = local.L.LoadCatchUp(tx, true, &local); err != nil {
		t.Fatal(err)
	}
	if local.R.CatchUp == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testOptionToOneSetOpCatchUpUsingCatchUp(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer tx.Rollback()

	var a Option
	var b, c CatchUp

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, optionDBTypes, false, strmangle.SetComplement(optionPrimaryKeyColumns, optionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, catchUpDBTypes, false, strmangle.SetComplement(catchUpPrimaryKeyColumns, catchUpColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, catchUpDBTypes, false, strmangle.SetComplement(catchUpPrimaryKeyColumns, catchUpColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*CatchUp{&b, &c} {
		err = a.SetCatchUp(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.CatchUp != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Options[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.CatchUpID != x.ID {
			t.Error("foreign key was wrong value", a.CatchUpID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.CatchUpID))
		reflect.Indirect(reflect.ValueOf(&a.CatchUpID)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.CatchUpID != x.ID {
			t.Error("foreign key was wrong value", a.CatchUpID, x.ID)
		}
	}
}
func testOptionsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	option := &Option{}
	if err = randomize.Struct(seed, option, optionDBTypes, true, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = option.Insert(tx); err != nil {
		t.Error(err)
	}

	if err = option.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testOptionsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	option := &Option{}
	if err = randomize.Struct(seed, option, optionDBTypes, true, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = option.Insert(tx); err != nil {
		t.Error(err)
	}

	slice := OptionSlice{option}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}
func testOptionsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	option := &Option{}
	if err = randomize.Struct(seed, option, optionDBTypes, true, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = option.Insert(tx); err != nil {
		t.Error(err)
	}

	slice, err := Options(tx).All()
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	optionDBTypes = map[string]string{`CatchUpID`: `int`, `CreatedAt`: `datetime`, `Date`: `datetime`, `ID`: `int`, `UpdatedAt`: `datetime`}
	_             = bytes.MinRead
)

func testOptionsUpdate(t *testing.T) {
	t.Parallel()

	if len(optionColumns) == len(optionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	option := &Option{}
	if err = randomize.Struct(seed, option, optionDBTypes, true, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = option.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Options(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, option, optionDBTypes, true, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	if err = option.Update(tx); err != nil {
		t.Error(err)
	}
}

func testOptionsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(optionColumns) == len(optionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	option := &Option{}
	if err = randomize.Struct(seed, option, optionDBTypes, true, optionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = option.Insert(tx); err != nil {
		t.Error(err)
	}

	count, err := Options(tx).Count()
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, option, optionDBTypes, true, optionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(optionColumns, optionPrimaryKeyColumns) {
		fields = optionColumns
	} else {
		fields = strmangle.SetComplement(
			optionColumns,
			optionPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(option))
	updateMap := M{}
	for _, col := range fields {
		updateMap[col] = value.FieldByName(strmangle.TitleCase(col)).Interface()
	}

	slice := OptionSlice{option}
	if err = slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	}
}
func testOptionsUpsert(t *testing.T) {
	t.Parallel()

	if len(optionColumns) == len(optionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	option := Option{}
	if err = randomize.Struct(seed, &option, optionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer tx.Rollback()
	if err = option.Upsert(tx, nil); err != nil {
		t.Errorf("Unable to upsert Option: %s", err)
	}

	count, err := Options(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &option, optionDBTypes, false, optionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Option struct: %s", err)
	}

	if err = option.Upsert(tx, nil); err != nil {
		t.Errorf("Unable to upsert Option: %s", err)
	}

	count, err = Options(tx).Count()
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
